# Palette adapted from zenbones-theme/zenbones.nvim (forestbones).
# License: MIT

"attribute" = "special"
"type" = "type"
"type.builtin" = { fg = "type", modifiers = ["bold"] }
"type.enum" = "type"
"type.enum.variant" = "type"
"constructor" = "type"
"constant" = { fg = "constant", modifiers = ['italic'] }
"constant.builtin.boolean" = { fg = "boolean", modifiers = ['italic'] }
"constant.character" = "character"
"constant.character.escape" = "special"
"constant.numeric" = "number"
"string" = { fg = "string", modifiers = ['italic'] }
"string.regexp" = "special"
"string.special" = "special"
"comment" = { fg = "comment", modifiers = ['italic'] }
"comment.line.documentation" = { fg = "comment", modifiers = ["bold"] }
"comment.block.documentation" = { fg = "comment", modifiers = ["bold"] }
"variable" = "identifier"
"variable.builtin" = "constant"
"variable.parameter" = "identifier"
"variable.other.member" = "identifier"
"label" = "special"
"punctuation" = "delimiter"
"punctuation.delimiter" = "delimiter"
"punctuation.special" = "special"
"keyword" = { fg = "statement", modifiers = ['bold'] }
"keyword.control.import" = "preproc"
"keyword.control.exception" = "error"
"operator" = "operator"
"function" = { fg = "function", modifiers = [] }
"function.builtin" = "function"
"function.macro" = "preproc"
"tag" = "type"
"namespace" = "preproc"
"special" = "special"
"markup.heading" = { fg = "title", modifiers = ["bold"] }
"markup.list" = "number"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "special", underline = { style = "line" } }
"markup.link.url" = { fg = "special", underline = { style = "line" } }
"markup.quote" = "comment"
"markup.raw" = "string"

"ui.background" = { fg = "foreground", bg = "background" }
"ui.cursor" = { fg = "cursor_fg", bg = "cursor_bg" }
"ui.cursor.primary" = { fg = "cursor_fg", bg = "cursor_bg" }
"ui.cursor.match" = { fg = "match", bg = "search_bg", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.linenr" = "linenr"
"ui.linenr.selected" = { fg = "linenr_selected", modifiers = ["bold"] }
"ui.statusline" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.inactive" = { fg = "status_inactive_fg", bg = "status_inactive_bg" }
"ui.statusline.normal" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.insert" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.select" = { fg = "status_fg", bg = "status_bg" }
"ui.popup" = { fg = "menu_fg", bg = "menu_bg" }
"ui.window" = { fg = "separator", bg = "background" }
"ui.help" = { fg = "menu_fg", bg = "menu_bg" }
"ui.text" = "foreground"
"ui.text.focus" = { modifiers = ["bold"] }
"ui.virtual" = "nontext"
"ui.virtual.ruler" = { bg = "colorcolumn" }
"ui.virtual.whitespace" = "nontext"
"ui.virtual.indent-guide" = "colorcolumn"
"ui.virtual.jump-label" = { fg = "special", modifiers = ["bold"] }
"ui.menu" = { fg = "menu_fg", bg = "menu_bg" }
"ui.menu.selected" = { fg = "menu_selected_fg", bg = "menu_selected_bg" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }
"diff.plus" = { fg = "diff_add_fg", bg = "diff_add_bg" }
"diff.minus" = { fg = "diff_delete_fg", bg = "diff_delete_bg" }
"diff.delta" = { fg = "diff_change_fg", bg = "diff_change_bg" }
"warning" = "warning"
"error" = "error"
"info" = "info"
"hint" = "hint"
"diagnostic" = { modifiers = [] }
"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
background = "#2c343a"
foreground = "#e7dcc4"
comment = "#6e7b85"
constant = "#ada28b"
boolean = "#e7dcc4"
character = "#ada28b"
string = "#ada28b"
identifier = "#c6baa0"
statement = "#a9c181"
preproc = "#83c193"
type = "#7fbcb4"
special = "#b5aa92"
function = "#e7dcc4"
number = "#ada28b"
operator = "#7b8e9d"
delimiter = "#7b8e9d"
error = "#e67c7f"
warning = "#ddbd7f"
info = "#7fbcb4"
hint = "#d69ab7"
cursor_fg = "#2c343a"
cursor_bg = "#ebe2cf"
cursorline = "#313a41"
linenr = "#667783"
linenr_selected = "#e7dcc4"
status_fg = "#e7dcc4"
status_bg = "#3e4850"
status_inactive_fg = "#ede5d4"
status_inactive_bg = "#353f46"
menu_fg = "#e7dcc4"
menu_bg = "#3b464e"
menu_selected_fg = "#e7dcc4"
menu_selected_bg = "#4e5b65"
selection = "#615b51"
search_fg = "#e7dcc4"
search_bg = "#9e5179"
incsearch_fg = "#2c343a"
incsearch_bg = "#dfb2c7"
diff_add_fg = "#a9c181"
diff_add_bg = "#3e482d"
diff_change_fg = "#7fbcb4"
diff_change_bg = "#304946"
diff_delete_fg = "#e67c7f"
diff_delete_bg = "#643839"
diff_text_bg = "#456763"
fold_fg = "#9cb4c6"
fold_bg = "#424d55"
nontext = "#5d6d78"
colorcolumn = "#685a41"
separator = "#667783"
float_border = "#798b9a"
title = "#e7dcc4"
match = "#e7dcc4"
