# Palette adapted from zenbones-theme/zenbones.nvim (forestbones).
# License: MIT

"attribute" = "special"
"type" = "type"
"type.builtin" = { fg = "type", modifiers = ["bold"] }
"type.enum" = "type"
"type.enum.variant" = "type"
"constructor" = "type"
"constant" = { fg = "constant", modifiers = ['italic'] }
"constant.builtin.boolean" = { fg = "boolean", modifiers = ['italic'] }
"constant.character" = "character"
"constant.character.escape" = "special"
"constant.numeric" = "number"
"string" = { fg = "string", modifiers = ['italic'] }
"string.regexp" = "special"
"string.special" = "special"
"comment" = { fg = "comment", modifiers = ['italic'] }
"comment.line.documentation" = { fg = "comment", modifiers = ["bold"] }
"comment.block.documentation" = { fg = "comment", modifiers = ["bold"] }
"variable" = "identifier"
"variable.builtin" = "constant"
"variable.parameter" = "identifier"
"variable.other.member" = "identifier"
"label" = "special"
"punctuation" = "delimiter"
"punctuation.delimiter" = "delimiter"
"punctuation.special" = "special"
"keyword" = { fg = "statement", modifiers = ['bold'] }
"keyword.control.import" = "preproc"
"keyword.control.exception" = "error"
"operator" = "operator"
"function" = { fg = "function", modifiers = [] }
"function.builtin" = "function"
"function.macro" = "preproc"
"tag" = "type"
"namespace" = "preproc"
"special" = "special"
"markup.heading" = { fg = "title", modifiers = ["bold"] }
"markup.list" = "number"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "special", underline = { style = "line" } }
"markup.link.url" = { fg = "special", underline = { style = "line" } }
"markup.quote" = "comment"
"markup.raw" = "string"

"ui.background" = { fg = "foreground", bg = "background" }
"ui.cursor" = { fg = "cursor_fg", bg = "cursor_bg" }
"ui.cursor.primary" = { fg = "cursor_fg", bg = "cursor_bg" }
"ui.cursor.match" = { fg = "match", bg = "search_bg", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.linenr" = "linenr"
"ui.linenr.selected" = { fg = "linenr_selected", modifiers = ["bold"] }
"ui.statusline" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.inactive" = { fg = "status_inactive_fg", bg = "status_inactive_bg" }
"ui.statusline.normal" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.insert" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.select" = { fg = "status_fg", bg = "status_bg" }
"ui.popup" = { fg = "menu_fg", bg = "menu_bg" }
"ui.window" = { fg = "separator", bg = "background" }
"ui.help" = { fg = "menu_fg", bg = "menu_bg" }
"ui.text" = "foreground"
"ui.text.focus" = { modifiers = ["bold"] }
"ui.virtual" = "nontext"
"ui.virtual.ruler" = { bg = "colorcolumn" }
"ui.virtual.whitespace" = "nontext"
"ui.virtual.indent-guide" = "colorcolumn"
"ui.virtual.jump-label" = { fg = "special", modifiers = ["bold"] }
"ui.menu" = { fg = "menu_fg", bg = "menu_bg" }
"ui.menu.selected" = { fg = "menu_selected_fg", bg = "menu_selected_bg" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }
"diff.plus" = { fg = "diff_add_fg", bg = "diff_add_bg" }
"diff.minus" = { fg = "diff_delete_fg", bg = "diff_delete_bg" }
"diff.delta" = { fg = "diff_change_fg", bg = "diff_change_bg" }
"warning" = "warning"
"error" = "error"
"info" = "info"
"hint" = "hint"
"diagnostic" = { modifiers = [] }
"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
background = "#faf3e1"
foreground = "#4f5b62"
comment = "#9a9071"
constant = "#73848d"
boolean = "#4f5b62"
character = "#73848d"
string = "#73848d"
identifier = "#63727a"
statement = "#8da200"
preproc = "#36a87e"
type = "#3a94c4"
special = "#6e7f88"
function = "#4f5b62"
number = "#73848d"
operator = "#92865b"
delimiter = "#92865b"
error = "#f85550"
warning = "#dea000"
info = "#3a94c4"
hint = "#df69ba"
cursor_fg = "#faf3e1"
cursor_bg = "#4f5b62"
cursorline = "#f6ebc8"
linenr = "#a99b6a"
linenr_selected = "#4f5b62"
status_fg = "#4f5b62"
status_bg = "#e3d191"
status_inactive_fg = "#758690"
status_inactive_bg = "#f3e2aa"
menu_fg = "#4f5b62"
menu_bg = "#e9d795"
menu_selected_fg = "#4f5b62"
menu_selected_bg = "#cfbe83"
selection = "#d3dfe6"
search_fg = "#4f5b62"
search_bg = "#eebadb"
incsearch_fg = "#faf3e1"
incsearch_bg = "#df69ba"
diff_add_fg = "#8da200"
diff_add_bg = "#dde7bd"
diff_change_fg = "#3a94c4"
diff_change_bg = "#dce3eb"
diff_delete_fg = "#f85550"
diff_delete_bg = "#eedfdf"
diff_text_bg = "#b0c3d4"
fold_fg = "#5a5236"
fold_bg = "#dac98b"
nontext = "#c0b079"
colorcolumn = "#e9cdad"
separator = "#a99b6a"
float_border = "#7c724d"
title = "#4f5b62"
match = "#4f5b62"
