# Palette adapted from zenbones-theme/zenbones.nvim (zenbones).
# License: MIT

"attribute" = "special"
"type" = "type"
"type.builtin" = { fg = "type", modifiers = ["bold"] }
"type.enum" = "type"
"type.enum.variant" = "type"
"constructor" = "type"
"constant" = { fg = "constant", modifiers = ['italic'] }
"constant.builtin.boolean" = { fg = "boolean", modifiers = ['italic'] }
"constant.character" = "character"
"constant.character.escape" = "special"
"constant.numeric" = "number"
"string" = { fg = "string", modifiers = ['italic'] }
"string.regexp" = "special"
"string.special" = "special"
"comment" = { fg = "comment", modifiers = ['italic'] }
"comment.line.documentation" = { fg = "comment", modifiers = ["bold"] }
"comment.block.documentation" = { fg = "comment", modifiers = ["bold"] }
"variable" = "identifier"
"variable.builtin" = "constant"
"variable.parameter" = "identifier"
"variable.other.member" = "identifier"
"label" = "special"
"punctuation" = "delimiter"
"punctuation.delimiter" = "delimiter"
"punctuation.special" = "special"
"keyword" = { fg = "statement", modifiers = ['bold'] }
"keyword.control.import" = "preproc"
"keyword.control.exception" = "error"
"operator" = "operator"
"function" = { fg = "function", modifiers = [] }
"function.builtin" = "function"
"function.macro" = "preproc"
"tag" = "type"
"namespace" = "preproc"
"special" = "special"
"markup.heading" = { fg = "title", modifiers = ["bold"] }
"markup.list" = "number"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "special", underline = { style = "line" } }
"markup.link.url" = { fg = "special", underline = { style = "line" } }
"markup.quote" = "comment"
"markup.raw" = "string"

"ui.background" = { fg = "foreground", bg = "background" }
"ui.cursor" = { fg = "cursor_fg", bg = "cursor_bg" }
"ui.cursor.primary" = { fg = "cursor_fg", bg = "cursor_bg" }
"ui.cursor.match" = { fg = "match", bg = "search_bg", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.linenr" = "linenr"
"ui.linenr.selected" = { fg = "linenr_selected", modifiers = ["bold"] }
"ui.statusline" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.inactive" = { fg = "status_inactive_fg", bg = "status_inactive_bg" }
"ui.statusline.normal" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.insert" = { fg = "status_fg", bg = "status_bg" }
"ui.statusline.select" = { fg = "status_fg", bg = "status_bg" }
"ui.popup" = { fg = "menu_fg", bg = "menu_bg" }
"ui.window" = { fg = "separator", bg = "background" }
"ui.help" = { fg = "menu_fg", bg = "menu_bg" }
"ui.text" = "foreground"
"ui.text.focus" = { modifiers = ["bold"] }
"ui.virtual" = "nontext"
"ui.virtual.ruler" = { bg = "colorcolumn" }
"ui.virtual.whitespace" = "nontext"
"ui.virtual.indent-guide" = "colorcolumn"
"ui.virtual.jump-label" = { fg = "special", modifiers = ["bold"] }
"ui.menu" = { fg = "menu_fg", bg = "menu_bg" }
"ui.menu.selected" = { fg = "menu_selected_fg", bg = "menu_selected_bg" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }
"diff.plus" = { fg = "diff_add_fg", bg = "diff_add_bg" }
"diff.minus" = { fg = "diff_delete_fg", bg = "diff_delete_bg" }
"diff.delta" = { fg = "diff_change_fg", bg = "diff_change_bg" }
"warning" = "warning"
"error" = "error"
"info" = "info"
"hint" = "hint"
"diagnostic" = { modifiers = [] }
"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
background = "#f0edec"
foreground = "#2c363c"
comment = "#948985"
constant = "#556570"
boolean = "#2c363c"
character = "#556570"
string = "#556570"
identifier = "#44525b"
statement = "#2c363c"
preproc = "#4f5e68"
type = "#6a5549"
special = "#4f5e68"
function = "#2c363c"
number = "#556570"
operator = "#8e817b"
delimiter = "#8e817b"
error = "#a8334c"
warning = "#944927"
info = "#286486"
hint = "#88507d"
cursor_fg = "#f0edec"
cursor_bg = "#2c363c"
cursorline = "#e9e4e2"
linenr = "#a4968f"
linenr_selected = "#2c363c"
status_fg = "#2c363c"
status_bg = "#d6cdc9"
status_inactive_fg = "#596a76"
status_inactive_bg = "#e1dcd9"
menu_fg = "#2c363c"
menu_bg = "#dad3cf"
menu_selected_fg = "#2c363c"
menu_selected_bg = "#c4b6af"
selection = "#cbd9e3"
search_fg = "#2c363c"
search_bg = "#deb9d6"
incsearch_fg = "#f0edec"
incsearch_bg = "#c074b2"
diff_add_fg = "#4f6c31"
diff_add_bg = "#cbe5b8"
diff_change_fg = "#286486"
diff_change_bg = "#d4dee7"
diff_delete_fg = "#a8334c"
diff_delete_bg = "#ebd8da"
diff_text_bg = "#a9bed1"
fold_fg = "#564e4a"
fold_bg = "#cdc2bc"
nontext = "#bbaba3"
colorcolumn = "#e6c5bd"
separator = "#a4968f"
float_border = "#786d68"
title = "#2c363c"
match = "#2c363c"
